export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

// Auto-generated by Supabase. Do not edit manually.
export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          password_hash: string
          full_name: string
          role: 'admin' | 'user'
          is_active: boolean
          created_at: string
          updated_at: string
          last_login_at: string | null
          failed_login_attempts: number
          locked_until: string | null
          password_changed_at: string
          must_change_password: boolean
          device_verified: boolean
          device_token: string | null
          device_verified_at: string | null
          two_factor_enabled: boolean
          two_factor_secret: string | null
          backup_codes: string[] | null
          security_questions: Json | null
          pin_hash: string | null
          pin_attempts: number
          pin_locked_until: string | null
        }
        Insert: {
          id?: string
          email: string
          password_hash: string
          full_name: string
          role: 'admin' | 'user'
          is_active?: boolean
          created_at?: string
          updated_at?: string
          last_login_at?: string | null
          failed_login_attempts?: number
          locked_until?: string | null
          password_changed_at?: string
          must_change_password?: boolean
          device_verified?: boolean
          device_token?: string | null
          device_verified_at?: string | null
          two_factor_enabled?: boolean
          two_factor_secret?: string | null
          backup_codes?: string[] | null
          security_questions?: Json | null
          pin_hash?: string | null
          pin_attempts?: number
          pin_locked_until?: string | null
        }
        Update: {
          id?: string
          email?: string
          password_hash?: string
          full_name?: string
          role?: 'admin' | 'user'
          is_active?: boolean
          created_at?: string
          updated_at?: string
          last_login_at?: string | null
          failed_login_attempts?: number
          locked_until?: string | null
          password_changed_at?: string
          must_change_password?: boolean
          device_verified?: boolean
          device_token?: string | null
          device_verified_at?: string | null
          two_factor_enabled?: boolean
          two_factor_secret?: string | null
          backup_codes?: string[] | null
          security_questions?: Json | null
          pin_hash?: string | null
          pin_attempts?: number
          pin_locked_until?: string | null
        }
      }
      sessions: {
        Row: {
          id: string
          user_id: string
          token: string
          expires_at: string
          ip_address: string | null
          user_agent: string | null
          created_at: string
          last_activity: string
        }
        Insert: {
          id?: string
          user_id: string
          token: string
          expires_at: string
          ip_address?: string | null
          user_agent?: string | null
          created_at?: string
          last_activity?: string
        }
        Update: {
          id?: string
          user_id?: string
          token?: string
          expires_at?: string
          ip_address?: string | null
          user_agent?: string | null
          created_at?: string
          last_activity?: string
        }
      }
      activity_logs: {
        Row: {
          id: string
          user_id: string | null
          action: string
          resource_type: string | null
          resource_id: string | null
          details: Json | null
          ip_address: string | null
          user_agent: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id?: string | null
          action: string
          resource_type?: string | null
          resource_id?: string | null
          details?: Json | null
          ip_address?: string | null
          user_agent?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string | null
          action?: string
          resource_type?: string | null
          resource_id?: string | null
          details?: Json | null
          ip_address?: string | null
          user_agent?: string | null
          created_at?: string
        }
      }
      tasks: {
        Row: {
          id: string
          title: string
          description: string | null
          status: 'pending' | 'in_progress' | 'completed'
          priority: 'low' | 'medium' | 'high'
          category: string
          due_date: string | null
          is_pinned: boolean
          created_by: string
          created_at: string
          updated_at: string
          completed_at: string | null
          completed_by: string | null
          link: string | null
          document_ids: string[] | null
          notes: string[] | null
        }
        Insert: {
          id?: string
          title: string
          description?: string | null
          status?: 'pending' | 'in_progress' | 'completed'
          priority?: 'low' | 'medium' | 'high'
          category: string
          due_date?: string | null
          is_pinned?: boolean
          created_by: string
          created_at?: string
          updated_at?: string
          completed_at?: string | null
          completed_by?: string | null
          link?: string | null
          document_ids?: string[] | null
          notes?: string[] | null
        }
        Update: {
          id?: string
          title?: string
          description?: string | null
          status?: 'pending' | 'in_progress' | 'completed'
          priority?: 'low' | 'medium' | 'high'
          category?: string
          due_date?: string | null
          is_pinned?: boolean
          created_by?: string
          created_at?: string
          updated_at?: string
          completed_at?: string | null
          completed_by?: string | null
          link?: string | null
          document_ids?: string[] | null
          notes?: string[] | null
        }
      }
      task_assignments: {
        Row: {
          id: string
          task_id: string
          user_id: string
          assigned_at: string
          assigned_by: string
        }
        Insert: {
          id?: string
          task_id: string
          user_id: string
          assigned_at?: string
          assigned_by: string
        }
        Update: {
          id?: string
          task_id?: string
          user_id?: string
          assigned_at?: string
          assigned_by?: string
        }
      }
      travel_details: {
        Row: {
          id: string
          trip_id: string
          type: 'flight' | 'hotel' | 'car' | 'train' | 'other'
          provider: string | null
          confirmation_number: string | null
          departure_location: string | null
          arrival_location: string | null
          departure_time: string | null
          arrival_time: string | null
          notes: string | null
          created_by: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          trip_id: string
          type: 'flight' | 'hotel' | 'car' | 'train' | 'other'
          provider?: string | null
          confirmation_number?: string | null
          departure_location?: string | null
          arrival_location?: string | null
          departure_time?: string | null
          arrival_time?: string | null
          notes?: string | null
          created_by: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          trip_id?: string
          type?: 'flight' | 'hotel' | 'car' | 'train' | 'other'
          provider?: string | null
          confirmation_number?: string | null
          departure_location?: string | null
          arrival_location?: string | null
          departure_time?: string | null
          arrival_time?: string | null
          notes?: string | null
          created_by?: string
          created_at?: string
          updated_at?: string
        }
      }
      travel_preferences: {
        Row: {
          id: string
          user_id: string
          seat_preference: string | null
          meal_preference: string | null
          airline_preference: string | null
          hotel_chain_preference: string | null
          loyalty_programs: Json | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          seat_preference?: string | null
          meal_preference?: string | null
          airline_preference?: string | null
          hotel_chain_preference?: string | null
          loyalty_programs?: Json | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          seat_preference?: string | null
          meal_preference?: string | null
          airline_preference?: string | null
          hotel_chain_preference?: string | null
          loyalty_programs?: Json | null
          created_at?: string
          updated_at?: string
        }
      }
      passwords: {
        Row: {
          id: string
          service_name: string
          username: string
          password: string
          url: string | null
          category: string
          notes: string | null
          tags: string[] | null
          owner_id: string
          created_at: string
          updated_at: string
          last_changed: string | null
          last_used_at: string | null
          is_shared: boolean
          is_favorite: boolean
          shared_with: string[] | null
        }
        Insert: {
          id?: string
          service_name: string
          username: string
          password: string
          url?: string | null
          category: string
          notes?: string | null
          tags?: string[] | null
          owner_id: string
          created_at?: string
          updated_at?: string
          last_changed?: string | null
          last_used_at?: string | null
          is_shared?: boolean
          is_favorite?: boolean
          shared_with?: string[] | null
        }
        Update: {
          id?: string
          service_name?: string
          username?: string
          password?: string
          url?: string | null
          category?: string
          notes?: string | null
          tags?: string[] | null
          owner_id?: string
          created_at?: string
          updated_at?: string
          last_changed?: string | null
          last_used_at?: string | null
          is_shared?: boolean
          is_favorite?: boolean
          shared_with?: string[] | null
        }
      }
      announcements: {
        Row: {
          id: string
          title: string
          content: string
          is_pinned: boolean
          expires_at: string | null
          created_by: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          title: string
          content: string
          is_pinned?: boolean
          expires_at?: string | null
          created_by: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          title?: string
          content?: string
          is_pinned?: boolean
          expires_at?: string | null
          created_by?: string
          created_at?: string
          updated_at?: string
        }
      }
      doctors: {
        Row: {
          id: string
          name: string
          specialty: string
          phone: string | null
          email: string | null
          address: string | null
          notes: string | null
          portal_url: string | null
          portal_username: string | null
          portal_password_hint: string | null
          created_by: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          specialty: string
          phone?: string | null
          email?: string | null
          address?: string | null
          notes?: string | null
          portal_url?: string | null
          portal_username?: string | null
          portal_password_hint?: string | null
          created_by: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          specialty?: string
          phone?: string | null
          email?: string | null
          address?: string | null
          notes?: string | null
          portal_url?: string | null
          portal_username?: string | null
          portal_password_hint?: string | null
          created_by?: string
          created_at?: string
          updated_at?: string
        }
      }
      medications: {
        Row: {
          id: string
          user_id: string
          name: string
          dosage: string
          frequency: string
          prescribed_by: string | null
          start_date: string
          end_date: string | null
          refills_remaining: number | null
          notes: string | null
          created_by: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          name: string
          dosage: string
          frequency: string
          prescribed_by?: string | null
          start_date: string
          end_date?: string | null
          refills_remaining?: number | null
          notes?: string | null
          created_by: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          name?: string
          dosage?: string
          frequency?: string
          prescribed_by?: string | null
          start_date?: string
          end_date?: string | null
          refills_remaining?: number | null
          notes?: string | null
          created_by?: string
          created_at?: string
          updated_at?: string
        }
      }
      documents: {
        Row: {
          id: string
          title: string
          description: string | null
          file_name: string
          file_size: number
          file_type: string
          file_url: string
          category: string
          tags: string[] | null
          uploaded_by: string
          uploaded_at: string
          updated_at: string
          expires_at: string | null
          is_archived: boolean
          shared_with: string[] | null
        }
        Insert: {
          id?: string
          title: string
          description?: string | null
          file_name: string
          file_size: number
          file_type: string
          file_url: string
          category: string
          tags?: string[] | null
          uploaded_by: string
          uploaded_at?: string
          updated_at?: string
          expires_at?: string | null
          is_archived?: boolean
          shared_with?: string[] | null
        }
        Update: {
          id?: string
          title?: string
          description?: string | null
          file_name?: string
          file_size?: number
          file_type?: string
          file_url?: string
          category?: string
          tags?: string[] | null
          uploaded_by?: string
          uploaded_at?: string
          updated_at?: string
          expires_at?: string | null
          is_archived?: boolean
          shared_with?: string[] | null
        }
      }
      service_providers: {
        Row: {
          id: string
          name: string
          category: string
          phone: string | null
          email: string | null
          address: string | null
          notes: string | null
          created_by: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          category: string
          phone?: string | null
          email?: string | null
          address?: string | null
          notes?: string | null
          created_by: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          category?: string
          phone?: string | null
          email?: string | null
          address?: string | null
          notes?: string | null
          created_by?: string
          created_at?: string
          updated_at?: string
        }
      }
      inventory: {
        Row: {
          id: string
          name: string
          description: string | null
          category: string
          location: string | null
          value: number | null
          purchase_date: string | null
          serial_number: string | null
          model_number: string | null
          warranty_expires: string | null
          notes: string | null
          photo_url: string | null
          created_by: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          description?: string | null
          category: string
          location?: string | null
          value?: number | null
          purchase_date?: string | null
          serial_number?: string | null
          model_number?: string | null
          warranty_expires?: string | null
          notes?: string | null
          photo_url?: string | null
          created_by: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          description?: string | null
          category?: string
          location?: string | null
          value?: number | null
          purchase_date?: string | null
          serial_number?: string | null
          model_number?: string | null
          warranty_expires?: string | null
          notes?: string | null
          photo_url?: string | null
          created_by?: string
          created_at?: string
          updated_at?: string
        }
      }
      properties: {
        Row: {
          id: string
          name: string
          type: string
          address: string
          status: string
          notes: string | null
          created_by: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          type: string
          address: string
          status?: string
          notes?: string | null
          created_by: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          type?: string
          address?: string
          status?: string
          notes?: string | null
          created_by?: string
          created_at?: string
          updated_at?: string
        }
      }
      pets: {
        Row: {
          id: string
          name: string
          species: string
          breed: string | null
          birth_date: string | null
          weight: number | null
          microchip_number: string | null
          notes: string | null
          photo_url: string | null
          vet_id: string | null
          created_by: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          species: string
          breed?: string | null
          birth_date?: string | null
          weight?: number | null
          microchip_number?: string | null
          notes?: string | null
          photo_url?: string | null
          vet_id?: string | null
          created_by: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          species?: string
          breed?: string | null
          birth_date?: string | null
          weight?: number | null
          microchip_number?: string | null
          notes?: string | null
          photo_url?: string | null
          vet_id?: string | null
          created_by?: string
          created_at?: string
          updated_at?: string
        }
      }
      pet_medical_records: {
        Row: {
          id: string
          pet_id: string
          type: string
          date: string
          description: string | null
          provider: string | null
          notes: string | null
          documents: string[] | null
          created_by: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          pet_id: string
          type: string
          date: string
          description?: string | null
          provider?: string | null
          notes?: string | null
          documents?: string[] | null
          created_by: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          pet_id?: string
          type?: string
          date?: string
          description?: string | null
          provider?: string | null
          notes?: string | null
          documents?: string[] | null
          created_by?: string
          created_at?: string
          updated_at?: string
        }
      }
      email_verification_tokens: {
        Row: {
          id: string
          user_id: string
          token: string
          expires_at: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          token: string
          expires_at: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          token?: string
          expires_at?: string
          created_at?: string
        }
      }
      trusted_devices: {
        Row: {
          id: string
          user_id: string
          device_fingerprint: string
          device_name: string | null
          last_used_at: string
          created_at: string
          expires_at: string | null
        }
        Insert: {
          id?: string
          user_id: string
          device_fingerprint: string
          device_name?: string | null
          last_used_at?: string
          created_at?: string
          expires_at?: string | null
        }
        Update: {
          id?: string
          user_id?: string
          device_fingerprint?: string
          device_name?: string | null
          last_used_at?: string
          created_at?: string
          expires_at?: string | null
        }
      }
      calendar_events: {
        Row: {
          id: string
          title: string
          description: string | null
          start_time: string
          end_time: string
          all_day: boolean
          location: string | null
          category: string
          created_by: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          title: string
          description?: string | null
          start_time: string
          end_time: string
          all_day?: boolean
          location?: string | null
          category: string
          created_by: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          title?: string
          description?: string | null
          start_time?: string
          end_time?: string
          all_day?: boolean
          location?: string | null
          category?: string
          created_by?: string
          created_at?: string
          updated_at?: string
        }
      }
      categories: {
        Row: {
          id: string
          name: string
          color: string
          icon: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          color: string
          icon?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          color?: string
          icon?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      academic_children: {
        Row: {
          id: string
          name: string
          birth_date: string | null
          grade_level: string | null
          school_name: string | null
          notes: string | null
          created_by: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          birth_date?: string | null
          grade_level?: string | null
          school_name?: string | null
          notes?: string | null
          created_by: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          birth_date?: string | null
          grade_level?: string | null
          school_name?: string | null
          notes?: string | null
          created_by?: string
          created_at?: string
          updated_at?: string
        }
      }
      academic_contacts: {
        Row: {
          id: string
          child_id: string
          name: string
          role: string
          email: string | null
          phone: string | null
          notes: string | null
          created_by: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          child_id: string
          name: string
          role: string
          email?: string | null
          phone?: string | null
          notes?: string | null
          created_by: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          child_id?: string
          name?: string
          role?: string
          email?: string | null
          phone?: string | null
          notes?: string | null
          created_by?: string
          created_at?: string
          updated_at?: string
        }
      }
      academic_events: {
        Row: {
          id: string
          child_id: string
          title: string
          description: string | null
          event_date: string
          type: string
          created_by: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          child_id: string
          title: string
          description?: string | null
          event_date: string
          type: string
          created_by: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          child_id?: string
          title?: string
          description?: string | null
          event_date?: string
          type?: string
          created_by?: string
          created_at?: string
          updated_at?: string
        }
      }
      task_notes: {
        Row: {
          id: string
          task_id: string
          content: string
          created_by: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          task_id: string
          content: string
          created_by: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          task_id?: string
          content?: string
          created_by?: string
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: {}
    Functions: {}
    Enums: {}
    CompositeTypes: {}
  }
}
