name: Desktop Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
      - '*.*.*'

jobs:
  build-and-publish:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      SKIP_AUTO_UPDATE: '1'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint source (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: npm run lint

      - name: Build application
        run: npm run build

      - name: Package desktop app (macOS)
        if: matrix.os == 'macos-latest'
        run: npx electron-builder --publish always --mac dmg

      - name: Package desktop app (Windows)
        if: matrix.os == 'windows-latest'
        run: npx electron-builder --publish always --win nsis

      - name: Package desktop app (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: npx electron-builder --publish always --linux AppImage

      - name: Upload build artifacts
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: desktop-${{ matrix.os }}-artifacts
          path: |
            dist/*.dmg
            dist/*.zip
            dist/*.exe
            dist/*.AppImage
            dist/latest*.yml
          if-no-files-found: ignore
